# Generated by Django 3.2.9 on 2023-10-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('Events', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('is_public', models.BooleanField(default=True, verbose_name='Видно всем')),
                ('is_free', models.BooleanField(default=True, help_text='Если вход ограничен, обязательно отключите', verbose_name='Присоедениться могут все')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('FAQs', models.TextField(blank=True, null=True, verbose_name='FAQs')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт организации')),
                ('organizers_contacts', models.TextField(blank=True, null=True, verbose_name='Контакты оранизатора')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Время конца')),
                ('enter_GPS_lat', models.FloatField(blank=True, null=True, verbose_name='GPS (широта) входа')),
                ('enter_GPS_lon', models.FloatField(blank=True, null=True, verbose_name='GPS (долгота) входа')),
                ('enter_text', models.TextField(blank=True, null=True, verbose_name='Как добараться?')),
                ('area_GPS', models.TextField(blank=True, help_text='Пары значений (GPS широта и долгота) разеделенные переносом строки, обочающий зону мероприятия на карте', null=True, verbose_name='Облась мероприятия')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('enter_GPS_lat', models.FloatField(blank=True, null=True, verbose_name='GPS (широта) входа')),
                ('enter_GPS_lon', models.FloatField(blank=True, null=True, verbose_name='GPS (долгота) входа')),
                ('enter_text', models.TextField(blank=True, null=True, verbose_name='Как добараться?')),
                ('area_GPS', models.TextField(blank=True, help_text='Пары значений (GPS широта и долгота) разеделенные переносом строки, обочающий зону мероприятия на карте', null=True, verbose_name='Облась мероприятия')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Время конца')),
                ('leads_text', models.TextField(blank=True, null=True, verbose_name='Выступают')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
