# Generated by Django 3.2.9 on 2023-10-14 15:51

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='points',
            field=wagtail.fields.StreamField([('point', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('pref_or_hall', wagtail.blocks.PageChooserBlock(page_type=['Events.Hall', 'Events.Performance'])), ('text', wagtail.blocks.TextBlock())])))], default={}, use_json_field=True),
            preserve_default=False,
        ),
    ]
