# Generated by Django 3.2.9 on 2023-10-14 16:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_game_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='points',
            field=wagtail.fields.StreamField([('point', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('Performance_or_hall', wagtail.blocks.PageChooserBlock(help_text='Это выступление или зал будет связан с этим пунтом игры, учанитик получит информацию', page_type=['Events.Hall', 'Events.Performance'])), ('text', wagtail.blocks.TextBlock(help_text='Этот текст будет высвечиться вместе с сообщением о выступлении или зале, это может быть например загадка'))])))], help_text='Игра считается пройдейнной, если учасник прошел через вссе', use_json_field=True, verbose_name='Точки игры'),
        ),
    ]
