# Generated by Django 3.2.9 on 2023-10-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_alter_game_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('telegram_username', models.IntegerField(unique=True)),
                ('participated_in_events', models.ManyToManyField(to='Events.Event')),
                ('participated_in_games', models.ManyToManyField(to='Events.Game')),
            ],
        ),
    ]
