# Generated by Django 3.2.9 on 2023-10-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_telegramusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePoint2TelegramUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('game_id', models.IntegerField()),
                ('point_hash', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
