# Generated by Django 3.2.9 on 2023-10-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_gamepoint2telegramusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramusers',
            name='participated_in_events',
        ),
        migrations.RemoveField(
            model_name='telegramusers',
            name='participated_in_games',
        ),
    ]
