# Generated by Django 3.2.9 on 2023-10-15 08:34

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0009_auto_20231014_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partisipatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('page_id', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='points',
            field=wagtail.fields.StreamField([('point', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('Performance_or_hall', wagtail.blocks.PageChooserBlock(help_text='Это выступление или зал будет связан с этим пунтом игры, учанитик получит информацию', page_type=['Events.Hall', 'Events.Performance'], required=False)), ('text', wagtail.blocks.TextBlock(help_text='Этот текст будет высвечиться вместе с сообщением о выступлении или зале, это может быть например загадка')), ('answers', wagtail.blocks.TextBlock(help_text='Правильные варинты ответа по каждому на строку, регистр, пробельные и служебные символы  не учиываеються', required=False))])))], help_text='Игра считается пройдейнной, если учасник прошел через вссе', use_json_field=True, verbose_name='Точки игры'),
        ),
    ]
